[package]
name = "butterfly"
version = "0.1.0"
edition = "2021"

[dependencies]
libafl = "0.7.1"
pcap = "0.9.2"
serde = "1.0.137"

[patch.crates-io]
libafl = { git = "https://github.com/AFLplusplus/LibAFL" }
