[package]
name = "butterfly"
version = "0.1.0"
edition = "2021"
authors = ["Patrick D."]
description = "LibAFL components for stateful fuzzing"
readme = "README.md"
repository = "https://github.com/fkie-cad/butterfly"
license = "MIT"
keywords = ["libafl", "fuzzing", "security"]
include = [
    "src/*",
    "Cargo.toml",
    "README.md",
]

[dependencies]
libafl = "0.7.1"
pcap = "0.9.2"
serde = "1.0.137"

[patch.crates-io]
libafl = { git = "https://github.com/AFLplusplus/LibAFL" }
