[package]
name = "minimal_ftp_fuzzer"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = true
codegen-units = 1
debug = true

[dependencies]
libafl = "0.8"
butterfly = { path = "../../", package = "butterfly-fuzz", features = ["graphviz"] }
serde = "1.0"
pcap = "0.9"
etherparse = "0.11"
